language: ruby
rvm:
  - ree-1.8.7-2012.02
  - 2.1.5
  - 2.2
sudo: false     # makes build run in docker container, which starts faster than a VM
cache: bundler  # speed up
before_script:
  - mysql -e 'create database sql_partitioner_test;'
script:
  - bundle exec rspec
